### ISSUE TITLE
Is there real need for >> 1 and << 1 everywhere?

### ISSUE THREAD

**Issue by juanplopes** [felipernb/algorithms.js#96]
Can't modern javascript compilers optimize this kind of instructions? I know this is kind of bikeshedding, but I think using shifts instead of multiplications only sacrifices readability of the code.

**Comment by felipernb** [comment]
Can you point some cases? Sometimes it's the easier way to force integer division and avoid rounding down float numbers

**Comment by juanplopes** [comment]
Oh sorry, Javascript isn't my strong language. I completely forgot it has no built-in integer division. But the argument is still valid at least for multiplications.

**Comment by felipernb** [comment]
It's not a matter of optimization, but a matter of consistency instead. Wherever << comes as multiplication it's just because in the same piece of code >> is used for division and I wanted to keep the operations symmetrical.
